/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lap9p2_carlosbonilla;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lospe
 */
public class main extends javax.swing.JFrame {
String direccion;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        jb_Upload.setVisible(false);
        HiloTiempo h=new HiloTiempo(jl_Hora,jl_dia);
        Thread hilo1 = new Thread(h);
        hilo1.start();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_mainPanel = new javax.swing.JPanel();
        jb_archivos = new javax.swing.JButton();
        pb_loadingBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_Input = new javax.swing.JTextArea();
        jb_Upload = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jl_Hora = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jl_dia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_mainPanel.setBackground(new java.awt.Color(255, 153, 255));

        jb_archivos.setText("Seleccionar Archivo");
        jb_archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_archivosActionPerformed(evt);
            }
        });

        pb_loadingBar.setBackground(new java.awt.Color(255, 255, 255));

        tf_Input.setBackground(new java.awt.Color(255, 255, 255));
        tf_Input.setColumns(20);
        tf_Input.setRows(5);
        jScrollPane1.setViewportView(tf_Input);

        jb_Upload.setText("Sobreescribir Archivo");
        jb_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_UploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_mainPanelLayout = new javax.swing.GroupLayout(jp_mainPanel);
        jp_mainPanel.setLayout(jp_mainPanelLayout);
        jp_mainPanelLayout.setHorizontalGroup(
            jp_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mainPanelLayout.createSequentialGroup()
                .addGroup(jp_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mainPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jb_archivos)
                        .addGap(56, 56, 56)
                        .addComponent(jb_Upload))
                    .addGroup(jp_mainPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jp_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pb_loadingBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jp_mainPanelLayout.setVerticalGroup(
            jp_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mainPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jp_mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_archivos)
                    .addComponent(jb_Upload))
                .addGap(34, 34, 34)
                .addComponent(pb_loadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jl_Hora.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jl_Hora.setForeground(new java.awt.Color(0, 0, 0));
        jl_Hora.setText("hh:mm:ss");

        hora.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        hora.setForeground(new java.awt.Color(0, 0, 0));
        hora.setText("Hora");

        fecha.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setText("Fecha");

        jl_dia.setBackground(new java.awt.Color(255, 255, 255));
        jl_dia.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jl_dia.setForeground(new java.awt.Color(0, 0, 0));
        jl_dia.setText("dd/MM/yy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_Hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_dia, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_dia)
                .addGap(94, 94, 94)
                .addComponent(hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_archivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_archivosActionPerformed
        JFileChooser c=new JFileChooser("./");
        FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivos de texto", "txt");
        c.setFileFilter(filtro);
        FileReader fr=null;
        BufferedReader br=null;
        int select=c.showOpenDialog(jPanel3);
        
        if (select==JFileChooser.APPROVE_OPTION) {
            try{
                tf_Input.setText("");
                File archivo=c.getSelectedFile();
                direccion=archivo.getPath();
                fr=new FileReader(archivo);
                br=new BufferedReader(fr);
                String newText="";
                String linea;
                while((linea=br.readLine())!=null){
                    newText+=linea;
                    newText+="\n";
                }
                
                ProgresarBarra p=new ProgresarBarra(pb_loadingBar,newText,tf_Input);
                Thread hilitoBarra=new Thread(p);
                hilitoBarra.start();
                jb_Upload.setVisible(true);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jb_archivosActionPerformed

    private void jb_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_UploadActionPerformed
        FileWriter fw=null;
        BufferedWriter bw=null;
        File archivo=null;
         try{
    String newText=tf_Input.getText();
    archivo =new File(direccion);
    fw=new FileWriter(archivo);
    bw=new BufferedWriter(fw);
    
    bw.write(newText);
    bw.newLine();
    bw.flush();
    JOptionPane.showMessageDialog(this, "Archivo actualizado con exito");
    bw.close();
    fw.close();
}catch(Exception e){
     
}
    }//GEN-LAST:event_jb_UploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Upload;
    private javax.swing.JButton jb_archivos;
    private javax.swing.JLabel jl_Hora;
    private javax.swing.JLabel jl_dia;
    private javax.swing.JPanel jp_mainPanel;
    private javax.swing.JProgressBar pb_loadingBar;
    private javax.swing.JTextArea tf_Input;
    // End of variables declaration//GEN-END:variables
}
